### PR TITLE
use installed PHPUnit binary from vendor directory

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by xabbuh** [comment]
In fact this looks more like an incompatibility with PHPUnit 5.

@matthiasnoback Which solution do you prefer? Not supporting PHPUnit 5 for the moment or trying to fix this issue?

**Comment by matthiasnoback** [comment]
@xabbuh This is quite strange. I think we should first limit the PHPUnit version to <5, then merge your PRs, and finally try to fix compatibility with PHPUnit 5 as a new release.

**Comment by xabbuh** [comment]
I agree. See #53 which temporarily only allows to use PHPUnit 3 and 4 in tests.

**Comment by xabbuh** [comment]
closing in favour of #53

**Pull request closed without merging**
