### PR TITLE
swap actual and expected value in error message

### LINKED ISSUE #49: Expected/actual should be swapped for ContainerBuilderHasParameterConstraint
```
...
There was 1 failure:

1) Symfony\Cmf\Bundle\RoutingBundle\Tests\Unit\DependencyInjection\CmfRoutingExtensionTest::testRouteBasepathsMerging with data set #2 (null, array('/cms/test'), array('/cms/routes', '/cms/test'), '/cms/routes')
The value of parameter "cmf_routing.dynamic.persistence.phpcr.route_basepaths" (Array &0 (
    0 => '/cms/routes'
    1 => '/cms/test'
)) does not match the expected value (Array &0 (
    0 => '/cms/test'
))
Failed asserting that Symfony\Component\DependencyInjection\ContainerBuilder Object &000000004ae804bd0000000034c3290d (
    ...
    'parameterBag' => Symfony\Component\DependencyInjection\ParameterBag\ParameterBag Object &000000004ae8069d0000000034
c3290d (
        'parameters' => Array &5 (
            ...
            'cmf_routing.dynamic.persistence.phpcr.route_basepaths' => Array &11 (
                0 => '/cms/test'
            )
            ...
    )
    ...
) has a parameter "cmf_routing.dynamic.persistence.phpcr.route_basepaths" with the given value.
```

As you can see, the actual value of the parameter is `array('/cms/test')`, while the expected was `array('/cms/routes', '/cms/test')`. The failure message says the opposite.

### PR DESCRIPTION
**Pull request by xabbuh**
This fixes #49.

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Thanks! However, the build is failing. I guess this might have something to do with the fact that .travis.yml contains no "script" key (which should point to vendor/bin/phpunit instead of a pre-installed phpunit executable. Could you maybe look into this @xabbuh ?

**Comment by xabbuh** [comment]
@matthiasnoback Let's see if #51 fixes that issue.

**Comment by xabbuh** [comment]
rebased to take into account the changes from #53

**Comment by matthiasnoback** [comment]
Thanks for your perseverance!

**Comment by xabbuh** [comment]
Thanks for teaching me a new word. :)

**Comment by matthiasnoback** [comment]
Hehe :)

**Pull request merged**
